export const GET_TODOS_REQUEST="GET_TODOS_REQUEST"
export const GET_TODOS_SUCCESS="GET_TODOS_SUCCESS"
export const GET_TODOS_FAILURE="GET_TODOS_RFAILURE"

export const ADD_TODOS_REQUEST="ADD_TODOS_REQUEST"
export const ADD_TODOS_SUCCESS="ADD_TODOS_SUCCESS"
export const ADD_TODOS_FAILURE="ADD_TODOS_RFAILURE"

export const CHANGE_STATUS_REQUEST="CHANGE_STATUS_REQUEST"
export const CHANGE_STATUS_SUCCESFUL="CHANGE_STATUS_SUCCESFUL"
export const CHANGE_STATUS_FAILURE="CHANGE_STATUS_FAILURE"

export const DELETE_REQUEST="DELETE_REQUEST"
export const DELETE_SUCCESFUL="DELETE_SUCCESFUL"
export const DELETE_FAILURE="DELETE_FAILURE"
